version: '3.7'

services:

  sample:
    container_name: todo-backend
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3333:3322
    environment:
      - CHOKIDAR_USEPOLLING=true
